name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *' # di√°rio
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate contribution snake
        uses: tsparticles/github-contribution-grid-snake@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: 'output/github-contribution-grid-snake.svg'
      - name: Commit snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "chore: update contribution snake" || echo "no changes to commit"
          git push
